# Generated by Django 3.1.6 on 2021-08-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatid', models.CharField(blank=True, default='', max_length=5000)),
                ('program', models.CharField(blank=True, default='', max_length=100)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('second_last_name', models.CharField(blank=True, default='', max_length=100)),
                ('suffix', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.CharField(blank=True, default='', max_length=100)),
                ('last_four_social', models.CharField(blank=True, default='', max_length=100)),
                ('residential_address', models.CharField(blank=True, default='', max_length=100)),
                ('apt_unit1', models.CharField(blank=True, default='', max_length=100)),
                ('apt_unit2', models.CharField(blank=True, default='', max_length=100)),
                ('is_permanent', models.BooleanField(default=True)),
                ('address_nature', models.CharField(blank=True, default='', max_length=100)),
                ('form_filled', models.BooleanField(default=False)),
                ('shipping_address', models.CharField(blank=True, default='', max_length=100)),
                ('form_zip_code', models.CharField(blank=True, default='', max_length=100)),
                ('ServicePlan', models.CharField(blank=True, default='', max_length=30)),
                ('iehBool', models.BooleanField(default=False)),
                ('benefit_code', models.CharField(default='', max_length=10)),
                ('zap_acct', models.CharField(default='', max_length=10)),
                ('zap_name', models.CharField(default='', max_length=10)),
                ('sequence_count', models.CharField(default='0', max_length=5)),
                ('islifeline_service', models.CharField(blank=True, default='', max_length=20)),
                ('other_adult', models.CharField(blank=True, default='', max_length=20)),
                ('share_liveing_expesses', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('sequence_id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('type', models.CharField(max_length=40)),
            ],
        ),
    ]
